### ISSUE TITLE
uploadasset always times out.

### ISSUE THREAD

**Issue by trejakob** [mrteenageparker/script-builder#3]
some images:
https://gyazo.com/a25b3414e5eb9ed3961ba234f0047f1d
https://gyazo.com/2d2234b92971a25b858a143cd74ca8be

php file is unedited besides the account information

i dont really care at this point if someone changes password on that dummy account
php file: https://paste.ee/p/rsXF4

(and yes the server host executes other php scripts perfectly fine.)

**Comment by mrparkerlol** [comment]
If I recall - roblox forces usage of a captcha on all their login-related
API endpoints now. To fix, login to the account once in a browser and get
the .ROBLOSECURITY cookie and store it in the text file.

There’s no way iirc to automate logins on the website now.

Besides that the script should still work.

Edit: also make sure the host you are using allows the usage of the curl function and has cURL installed for php to use.

**Comment by trejakob** [comment]
Ok so i removed the getrs function and just made a global called $rs i also removed that weird loop that was causing that timeout all of the time so it returns the body even if theres an "error" and i also used xampp now because i was getting tired of updating the php file with filezilla. but i do get the same error on xampp and the host the really weird thing is that it redirects me to the roblox error page
(data.roblox.com/Data/Upload.ashx?json=1&name=SB_SCRIPT&description=SB_LOCAL_SCRIPT&genreTypeId=1&ispublic=True&allowComments=True&type=Model&assetId=0 is the page causing trouble)

i also noticed that i cant acces that page on firefox but i can on google chrome for some wierd reason

and btw i think you forgot to add $asset_upload in the global thingy

images:
https://gyazo.com/ddb80d4e146db69b45e2e578fe0df84a
https://gyazo.com/5279f3cfbd01195fd3ceeed0d6813f26

(also sorry for late response and probaly making you angry)

**Comment by mrparkerlol** [comment]
Try changing it to https:// in the url from http:// and remove the :80 from the url as well - and try that?

**Comment by trejakob** [comment]
nope still not working still redirects me to error page

**Comment by mrparkerlol** [comment]
Did you change in this file the upload URL?

https://github.com/mrteenageparker/sb-in-a-require/blob/master/SB/MainScript/MainModule/Config.lua

If not - if I understand correctly you are using your own code for publishing the module - try basing your code off of my code, if not then most likely ROBLOX changed their API and I am not too sure how to update in that case - but I will try to find a fix from friends.

**Comment by mrparkerlol** [comment]
I found out recently from a friend that you can use noblox - which has a method of authenticating using cookies purely:

https://github.com/suufi/noblox.js

I probably will write an incorporation of this into the project - but I will have to be motivated to do it.

For now this issue will remain open until I do that for a reminder.

**Comment by mrparkerlol** [comment]
Closing as this has been officially fixed now.

The following repo may be of help to you:
https://github.com/mrteenageparker/script-builder-backend

Also this script builder is currently going under a complete rewrite - I'd suggest re-taking the project when a official model is made.
